-- =====================================================
-- 档案管理系统测试数据库Schema (H2 2.x兼容)
-- 使用H2 PostgreSQL兼容模式
-- =====================================================

-- 1. 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(100),
    email VARCHAR(100),
    phone VARCHAR(20),
    department VARCHAR(100),
    user_type VARCHAR(30) DEFAULT 'USER',
    status VARCHAR(20) DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 2. 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

-- 3. 用户角色关联表
CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);

-- 4. 系统配置表
CREATE TABLE IF NOT EXISTS sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value TEXT,
    config_type VARCHAR(50) DEFAULT 'STRING',
    config_group VARCHAR(50),
    description VARCHAR(500),
    editable BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

-- 5. 全宗表
CREATE TABLE IF NOT EXISTS arc_fonds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonds_no VARCHAR(50) NOT NULL UNIQUE,
    fonds_name VARCHAR(200) NOT NULL,
    fonds_type VARCHAR(50),
    description TEXT,
    contact_person VARCHAR(100),
    contact_phone VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 6. 档案分类表
CREATE TABLE IF NOT EXISTS arc_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(200) NOT NULL,
    archive_type VARCHAR(50),
    level INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    retention_period VARCHAR(20),
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    full_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 7. 保管期限表
CREATE TABLE IF NOT EXISTS arc_retention_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_code VARCHAR(20) NOT NULL UNIQUE,
    period_name VARCHAR(50) NOT NULL,
    period_years INTEGER,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 档案表
CREATE TABLE IF NOT EXISTS arc_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_no VARCHAR(100) NOT NULL UNIQUE,
    fonds_id BIGINT,
    fonds_no VARCHAR(50),
    category_id BIGINT,
    category_code VARCHAR(50),
    archive_type VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    file_no VARCHAR(100),
    responsibility VARCHAR(200),
    archive_date DATE,
    document_date DATE,
    page_count INTEGER,
    pieces_count INTEGER DEFAULT 1,
    retention_period VARCHAR(20) NOT NULL,
    retention_expire_date DATE,
    security_level VARCHAR(20) DEFAULT 'INTERNAL',
    security_expire_date DATE,
    source_type VARCHAR(50),
    source_system VARCHAR(100),
    source_id VARCHAR(100),
    source_no VARCHAR(100),
    case_no VARCHAR(100),
    case_name VARCHAR(200),
    case_type VARCHAR(50),
    client_name VARCHAR(100),
    lawyer_name VARCHAR(100),
    case_status VARCHAR(50),
    case_close_date DATE,
    archive_form VARCHAR(20) DEFAULT 'ELECTRONIC',
    has_electronic BOOLEAN DEFAULT TRUE,
    has_physical BOOLEAN DEFAULT FALSE,
    location_id BIGINT,
    storage_location VARCHAR(200),
    box_no VARCHAR(100),
    total_file_size BIGINT DEFAULT 0,
    file_count INTEGER DEFAULT 0,
    status VARCHAR(30) DEFAULT 'RECEIVED',
    received_at TIMESTAMP,
    received_by BIGINT,
    cataloged_at TIMESTAMP,
    cataloged_by BIGINT,
    archived_at TIMESTAMP,
    archived_by BIGINT,
    appraisal_date DATE,
    appraisal_result VARCHAR(50),
    destroy_date DATE,
    callback_url VARCHAR(500),
    keywords VARCHAR(500),
    "abstract" TEXT,
    remarks VARCHAR(500),
    extra_data TEXT,
    filing_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 9. 数字化文件表
CREATE TABLE IF NOT EXISTS arc_digital_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255),
    file_extension VARCHAR(20),
    mime_type VARCHAR(100),
    file_size BIGINT DEFAULT 0,
    hash_value VARCHAR(128),
    storage_path VARCHAR(500),
    thumbnail_path VARCHAR(500),
    preview_path VARCHAR(500),
    has_preview BOOLEAN DEFAULT FALSE,
    volume_no INTEGER,
    section_type VARCHAR(50),
    document_no VARCHAR(100),
    page_start INTEGER,
    page_end INTEGER,
    version_label VARCHAR(100),
    file_source_type VARCHAR(50) DEFAULT 'IMPORTED',
    source_url VARCHAR(1000),
    scan_batch_no VARCHAR(100),
    scan_operator VARCHAR(100),
    scan_time TIMESTAMP,
    scan_check_status VARCHAR(20),
    scan_check_by VARCHAR(100),
    scan_check_time TIMESTAMP,
    upload_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uploaded_by BIGINT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

-- 10. 借阅申请表
CREATE TABLE IF NOT EXISTS arc_borrow_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no VARCHAR(50) NOT NULL UNIQUE,
    archive_id BIGINT NOT NULL,
    archive_no VARCHAR(100),
    archive_title VARCHAR(500),
    applicant_id BIGINT NOT NULL,
    applicant_name VARCHAR(100),
    department VARCHAR(100),
    borrow_type VARCHAR(30) DEFAULT 'BORROW',
    borrow_purpose TEXT,
    expected_return_date DATE,
    actual_borrow_date DATE,
    actual_return_date DATE,
    status VARCHAR(30) DEFAULT 'PENDING',
    approver_id BIGINT,
    approver_name VARCHAR(100),
    approve_time TIMESTAMP,
    approve_comment TEXT,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 11. 操作日志表
CREATE TABLE IF NOT EXISTS arc_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(50),
    operation VARCHAR(100) NOT NULL,
    method VARCHAR(500),
    params TEXT,
    result TEXT,
    ip_address VARCHAR(50),
    execution_time BIGINT,
    status VARCHAR(20) DEFAULT 'SUCCESS',
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. 访问日志表
CREATE TABLE IF NOT EXISTS arc_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(50),
    resource_type VARCHAR(50),
    resource_id BIGINT,
    action VARCHAR(50),
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. 档案元数据表
CREATE TABLE IF NOT EXISTS arc_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    meta_key VARCHAR(100) NOT NULL,
    meta_value TEXT,
    meta_type VARCHAR(50) DEFAULT 'STRING',
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 14. 外部来源配置表
CREATE TABLE IF NOT EXISTS arc_external_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(50) NOT NULL UNIQUE,
    source_name VARCHAR(100) NOT NULL,
    source_type VARCHAR(50),
    api_url VARCHAR(500),
    api_key VARCHAR(255),
    callback_url VARCHAR(500),
    config_data TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 15. 鉴定记录表
CREATE TABLE IF NOT EXISTS arc_appraisal_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    archive_no VARCHAR(100),
    appraisal_type VARCHAR(50),
    appraisal_result VARCHAR(50),
    original_retention VARCHAR(20),
    new_retention VARCHAR(20),
    appraiser_id BIGINT,
    appraiser_name VARCHAR(100),
    appraisal_date DATE,
    appraisal_comment TEXT,
    status VARCHAR(30) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- 16. 销毁记录表
CREATE TABLE IF NOT EXISTS arc_destruction_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    archive_no VARCHAR(100),
    archive_title VARCHAR(500),
    destruction_type VARCHAR(50),
    destruction_reason TEXT,
    appraisal_record_id BIGINT,
    destroyer_id BIGINT,
    destroyer_name VARCHAR(100),
    destruction_date DATE,
    witness_name VARCHAR(100),
    status VARCHAR(30) DEFAULT 'PENDING',
    approval_id BIGINT,
    approval_name VARCHAR(100),
    approval_date DATE,
    approval_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- =====================================================
-- 初始化测试数据
-- =====================================================

-- 插入测试用户 (密码: admin123 -> BCrypt加密)
INSERT INTO sys_user (id, username, password, real_name, email, phone, user_type, status) 
VALUES (1, 'admin', '$2a$10$OlfPXeGl2I6aNlrEw514QOGSQBhuYwpu8nIJZYJG7yO/AgJLyRp0u', '系统管理员', 'admin@archive.com', '13800138000', 'SYSTEM_ADMIN', 'ACTIVE');

INSERT INTO sys_user (id, username, password, real_name, email, phone, user_type, status) 
VALUES (2, 'testuser', '$2a$10$OlfPXeGl2I6aNlrEw514QOGSQBhuYwpu8nIJZYJG7yO/AgJLyRp0u', '测试用户', 'test@archive.com', '13900139000', 'USER', 'ACTIVE');

-- 插入测试角色
INSERT INTO sys_role (id, role_code, role_name, description, status) 
VALUES (1, 'ROLE_ADMIN', '系统管理员', '系统管理员拥有所有权限', 'ACTIVE');

INSERT INTO sys_role (id, role_code, role_name, description, status) 
VALUES (2, 'ROLE_ARCHIVE_ADMIN', '档案管理员', '档案管理所有权限', 'ACTIVE');

INSERT INTO sys_role (id, role_code, role_name, description, status) 
VALUES (3, 'ROLE_USER', '普通用户', '普通用户权限', 'ACTIVE');

-- 插入用户角色关联
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO sys_user_role (user_id, role_id) VALUES (2, 3);

-- 插入系统配置
INSERT INTO sys_config (config_key, config_value, config_type, config_group, description) VALUES
('archive.no.prefix', 'ARC', 'STRING', 'archive', '档案号前缀'),
('archive.no.date.format', 'yyyy', 'STRING', 'archive', '档案号日期格式'),
('borrow.max.days', '30', 'INTEGER', 'borrow', '最大借阅天数'),
('upload.max.size', '104857600', 'INTEGER', 'upload', '最大上传文件大小(字节)');

-- 插入保管期限
INSERT INTO arc_retention_period (id, period_code, period_name, period_years, sort_order) VALUES
(1, 'PERMANENT', '永久', NULL, 1),
(2, 'Y30', '30年', 30, 2),
(3, 'Y15', '15年', 15, 3),
(4, 'Y10', '10年', 10, 4),
(5, 'Y5', '5年', 5, 5);

-- 插入测试全宗
INSERT INTO arc_fonds (id, fonds_no, fonds_name, description, status) 
VALUES (1, 'F001', '律所档案全宗', '律师事务所档案全宗', 'ACTIVE');

-- 插入测试分类
INSERT INTO arc_category (id, parent_id, category_code, category_name, archive_type, sort_order, status, level) 
VALUES (1, NULL, '01', '诉讼档案', 'DOCUMENT', 1, 'ACTIVE', 1);

INSERT INTO arc_category (id, parent_id, category_code, category_name, archive_type, sort_order, status, level) 
VALUES (2, NULL, '02', '非诉讼档案', 'DOCUMENT', 2, 'ACTIVE', 1);

INSERT INTO arc_category (id, parent_id, category_code, category_name, archive_type, sort_order, status, level) 
VALUES (3, 1, '0101', '民事诉讼', 'DOCUMENT', 1, 'ACTIVE', 2);

INSERT INTO arc_category (id, parent_id, category_code, category_name, archive_type, sort_order, status, level) 
VALUES (4, 1, '0102', '刑事诉讼', 'DOCUMENT', 2, 'ACTIVE', 2);

-- 插入测试档案
INSERT INTO arc_archive (id, archive_no, fonds_id, fonds_no, category_id, category_code, archive_type, title, 
    file_no, responsibility, retention_period, security_level, source_type, status, page_count, file_count)
VALUES (1, 'ARC-2026-0001', 1, 'F001', 3, '0101', 'DOCUMENT', '张三诉李四合同纠纷案', 
    'CASE-2026-001', '张律师', 'Y10', 'INTERNAL', 'LAW_FIRM', 'RECEIVED', 50, 3);

INSERT INTO arc_archive (id, archive_no, fonds_id, fonds_no, category_id, category_code, archive_type, title, 
    file_no, responsibility, retention_period, security_level, source_type, status, page_count, file_count)
VALUES (2, 'ARC-2026-0002', 1, 'F001', 4, '0102', 'DOCUMENT', '王五故意伤害案', 
    'CASE-2026-002', '李律师', 'Y30', 'SECRET', 'LAW_FIRM', 'STORED', 120, 5);
