-- =====================================================
-- 档案管理系统测试数据库 Schema（当前模型兼容版）
-- 面向 H2 PostgreSQL 兼容模式
-- =====================================================

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    real_name VARCHAR(100),
    email VARCHAR(100),
    phone VARCHAR(20),
    department VARCHAR(100),
    user_type VARCHAR(30) DEFAULT 'USER',
    status VARCHAR(20) DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    UNIQUE(user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value TEXT,
    config_type VARCHAR(50) DEFAULT 'STRING',
    config_group VARCHAR(50),
    description VARCHAR(500),
    editable BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE TABLE IF NOT EXISTS arc_backup_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    local_path VARCHAR(1000),
    smb_host VARCHAR(255),
    smb_port INTEGER DEFAULT 445,
    smb_share VARCHAR(255),
    smb_username VARCHAR(255),
    smb_password_encrypted TEXT,
    smb_sub_path VARCHAR(500),
    remarks TEXT,
    verify_status VARCHAR(20) DEFAULT 'PENDING',
    verify_message VARCHAR(500),
    last_verified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE TABLE IF NOT EXISTS arc_backup_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_no VARCHAR(50) NOT NULL UNIQUE,
    target_id BIGINT,
    target_name VARCHAR(200),
    trigger_type VARCHAR(20) DEFAULT 'MANUAL',
    backup_scope VARCHAR(100),
    status VARCHAR(20) DEFAULT 'PENDING',
    backup_set_path VARCHAR(1000),
    file_count BIGINT DEFAULT 0,
    total_bytes BIGINT DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    operator_id BIGINT,
    operator_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arc_restore_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restore_no VARCHAR(50) NOT NULL UNIQUE,
    source_type VARCHAR(20) NOT NULL,
    target_id BIGINT,
    target_name VARCHAR(200),
    backup_set_name VARCHAR(255),
    status VARCHAR(20) DEFAULT 'PENDING',
    verify_status VARCHAR(20),
    restored_database BOOLEAN DEFAULT FALSE,
    restored_files BOOLEAN DEFAULT FALSE,
    restored_config BOOLEAN DEFAULT FALSE,
    rebuild_index_status VARCHAR(20),
    restore_report TEXT,
    error_message TEXT,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    operator_id BIGINT,
    operator_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key VARCHAR(64) NOT NULL UNIQUE,
    source_name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    expire_at TIMESTAMP,
    last_used_at TIMESTAMP,
    total_calls BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS sys_security_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    user_id BIGINT,
    username VARCHAR(50),
    ip_address VARCHAR(50),
    user_agent TEXT,
    details TEXT,
    event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_ip_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    ip_range VARCHAR(45),
    reason TEXT,
    blocked_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT
);

CREATE TABLE IF NOT EXISTS arc_fonds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonds_no VARCHAR(50) NOT NULL UNIQUE,
    fonds_name VARCHAR(200) NOT NULL,
    fonds_type VARCHAR(50),
    description TEXT,
    contact_person VARCHAR(100),
    contact_phone VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(200) NOT NULL,
    archive_type VARCHAR(50),
    level INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    retention_period VARCHAR(20),
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    full_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_retention_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_code VARCHAR(20) NOT NULL UNIQUE,
    period_name VARCHAR(50) NOT NULL,
    period_years INTEGER,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arc_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_no VARCHAR(100) NOT NULL UNIQUE,
    fonds_id BIGINT,
    fonds_no VARCHAR(50),
    category_id BIGINT,
    category_code VARCHAR(50),
    archive_type VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    file_no VARCHAR(100),
    responsibility VARCHAR(200),
    archive_date DATE,
    document_date DATE,
    page_count INTEGER,
    pieces_count INTEGER DEFAULT 1,
    retention_period VARCHAR(20) NOT NULL,
    retention_expire_date DATE,
    security_level VARCHAR(20) DEFAULT 'INTERNAL',
    security_expire_date DATE,
    source_type VARCHAR(50) NOT NULL,
    source_system VARCHAR(100),
    source_id VARCHAR(100),
    source_no VARCHAR(100),
    callback_url VARCHAR(500),
    case_no VARCHAR(100),
    case_name VARCHAR(500),
    client_name VARCHAR(200),
    lawyer_name VARCHAR(100),
    case_close_date DATE,
    archive_form VARCHAR(30) DEFAULT 'ELECTRONIC',
    has_electronic BOOLEAN DEFAULT TRUE,
    has_physical BOOLEAN DEFAULT FALSE,
    location_id BIGINT,
    storage_location VARCHAR(200),
    box_no VARCHAR(50),
    total_file_size BIGINT DEFAULT 0,
    file_count INTEGER DEFAULT 0,
    status VARCHAR(30) DEFAULT 'RECEIVED',
    received_at TIMESTAMP,
    received_by BIGINT,
    cataloged_at TIMESTAMP,
    cataloged_by BIGINT,
    archived_at TIMESTAMP,
    archived_by BIGINT,
    keywords TEXT,
    "abstract" TEXT,
    remarks TEXT,
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_digital_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT,
    file_no VARCHAR(50),
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255),
    file_extension VARCHAR(20),
    mime_type VARCHAR(100),
    file_size BIGINT DEFAULT 0,
    storage_path VARCHAR(500),
    storage_bucket VARCHAR(100),
    format_name VARCHAR(100),
    format_version VARCHAR(50),
    is_long_term_format BOOLEAN DEFAULT FALSE,
    converted_path VARCHAR(500),
    hash_algorithm VARCHAR(20) DEFAULT 'SHA256',
    hash_value VARCHAR(128),
    ocr_status VARCHAR(20),
    ocr_content TEXT,
    has_preview BOOLEAN DEFAULT FALSE,
    preview_path VARCHAR(500),
    thumbnail_path VARCHAR(500),
    file_category VARCHAR(50) DEFAULT 'MAIN',
    sort_order INTEGER DEFAULT 0,
    description TEXT,
    volume_no INTEGER,
    section_type VARCHAR(50),
    document_no VARCHAR(100),
    page_start INTEGER,
    page_end INTEGER,
    version_label VARCHAR(100),
    file_source_type VARCHAR(50) DEFAULT 'IMPORTED',
    source_url VARCHAR(1000),
    scan_batch_no VARCHAR(100),
    scan_operator VARCHAR(100),
    scan_time TIMESTAMP,
    scan_check_status VARCHAR(20),
    scan_check_by VARCHAR(100),
    scan_check_time TIMESTAMP,
    upload_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    upload_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    field_code VARCHAR(100) NOT NULL,
    field_name VARCHAR(200),
    field_value TEXT,
    field_type VARCHAR(50) DEFAULT 'TEXT',
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(archive_id, field_code)
);

CREATE TABLE IF NOT EXISTS arc_borrow_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no VARCHAR(50) NOT NULL UNIQUE,
    archive_id BIGINT NOT NULL,
    archive_no VARCHAR(100),
    archive_title VARCHAR(500),
    applicant_id BIGINT,
    applicant_name VARCHAR(100),
    applicant_dept VARCHAR(100),
    applicant_phone VARCHAR(50),
    apply_time TIMESTAMP,
    borrow_purpose TEXT,
    borrow_type VARCHAR(20) DEFAULT 'ONLINE',
    expected_return_date DATE,
    actual_return_date DATE,
    borrow_time TIMESTAMP,
    renew_count INTEGER DEFAULT 0,
    status VARCHAR(30) DEFAULT 'PENDING',
    approver_id BIGINT,
    approver_name VARCHAR(100),
    approve_time TIMESTAMP,
    approve_remarks TEXT,
    reject_reason TEXT,
    return_remarks TEXT,
    download_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    last_access_at TIMESTAMP,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_borrow_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrow_id BIGINT,
    archive_id BIGINT NOT NULL,
    archive_no VARCHAR(100),
    access_token VARCHAR(100) NOT NULL UNIQUE,
    source_type VARCHAR(50),
    source_system VARCHAR(100),
    source_user_id VARCHAR(100),
    source_user_name VARCHAR(100),
    borrow_purpose TEXT,
    expire_at TIMESTAMP NOT NULL,
    max_access_count INTEGER,
    allow_download BOOLEAN DEFAULT TRUE,
    access_count INTEGER DEFAULT 0,
    download_count INTEGER DEFAULT 0,
    last_access_at TIMESTAMP,
    last_access_ip VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    revoke_reason TEXT,
    revoked_at TIMESTAMP,
    revoked_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT
);

CREATE TABLE IF NOT EXISTS arc_dead_letter_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(100),
    queue_name VARCHAR(100) NOT NULL,
    routing_key VARCHAR(100),
    message_body TEXT NOT NULL,
    archive_id BIGINT,
    source_type VARCHAR(50),
    source_id VARCHAR(100),
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    status VARCHAR(20) DEFAULT 'PENDING',
    processed_by BIGINT,
    processed_at TIMESTAMP,
    process_remark TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arc_appraisal_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT NOT NULL,
    appraisal_type VARCHAR(50) NOT NULL,
    original_value VARCHAR(100),
    new_value VARCHAR(100),
    appraisal_reason TEXT,
    appraisal_opinion TEXT,
    status VARCHAR(30) DEFAULT 'PENDING',
    appraiser_id BIGINT,
    appraiser_name VARCHAR(100),
    appraised_at TIMESTAMP,
    approver_id BIGINT,
    approver_name VARCHAR(100),
    approved_at TIMESTAMP,
    approval_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_destruction_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destruction_batch_no VARCHAR(50) NOT NULL,
    archive_id BIGINT NOT NULL,
    destruction_reason TEXT,
    destruction_method VARCHAR(50),
    status VARCHAR(30) DEFAULT 'PENDING',
    proposer_id BIGINT,
    proposer_name VARCHAR(100),
    proposed_at TIMESTAMP,
    approver_id BIGINT,
    approver_name VARCHAR(100),
    approved_at TIMESTAMP,
    approval_comment TEXT,
    executor_id BIGINT,
    executor_name VARCHAR(100),
    executed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS archive_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code VARCHAR(50) NOT NULL UNIQUE,
    location_name VARCHAR(200) NOT NULL,
    room_name VARCHAR(100),
    area VARCHAR(50),
    shelf_no VARCHAR(50),
    layer_no VARCHAR(50),
    total_capacity INTEGER DEFAULT 0,
    used_capacity INTEGER DEFAULT 0,
    status VARCHAR(30) DEFAULT 'AVAILABLE',
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT,
    object_type VARCHAR(50) NOT NULL,
    object_id VARCHAR(100),
    operation_type VARCHAR(50) NOT NULL,
    operation_desc TEXT,
    operation_detail TEXT,
    operator_id BIGINT,
    operator_name VARCHAR(100),
    operator_ip VARCHAR(50),
    operator_ua TEXT,
    operated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS arc_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT,
    file_id BIGINT,
    access_type VARCHAR(30) NOT NULL,
    access_ip VARCHAR(50),
    access_ua TEXT,
    user_id BIGINT,
    user_name VARCHAR(100),
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    search_keyword VARCHAR(500),
    search_result_count INTEGER,
    duration BIGINT,
    extra_data TEXT
);

CREATE TABLE IF NOT EXISTS arc_external_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(50) NOT NULL UNIQUE,
    source_name VARCHAR(200) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    description TEXT,
    api_url VARCHAR(500),
    api_key TEXT,
    auth_type VARCHAR(50),
    extra_config TEXT,
    enabled BOOLEAN DEFAULT FALSE,
    last_sync_at TIMESTAMP,
    last_sync_status VARCHAR(20),
    last_sync_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_push_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    push_batch_no VARCHAR(50) NOT NULL,
    source_code VARCHAR(50),
    source_type VARCHAR(50) NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    source_no VARCHAR(100),
    archive_id BIGINT,
    archive_no VARCHAR(100),
    title VARCHAR(500),
    push_status VARCHAR(30) DEFAULT 'PENDING',
    file_status VARCHAR(30) DEFAULT 'PENDING',
    total_files INTEGER DEFAULT 0,
    success_files INTEGER DEFAULT 0,
    failed_files INTEGER DEFAULT 0,
    request_payload TEXT,
    callback_url VARCHAR(500),
    error_code VARCHAR(50),
    error_message TEXT,
    pushed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS arc_callback_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id BIGINT,
    archive_no VARCHAR(100),
    push_record_id BIGINT,
    callback_url VARCHAR(500) NOT NULL,
    callback_type VARCHAR(50) DEFAULT 'ARCHIVE_RECEIVED',
    callback_status VARCHAR(30) DEFAULT 'PENDING',
    request_body TEXT,
    response_code INTEGER,
    response_body TEXT,
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    next_retry_at TIMESTAMP,
    error_message TEXT,
    callback_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT FALSE
);

-- =====================================================
-- 初始化测试数据
-- =====================================================

INSERT INTO sys_user (id, username, password, real_name, email, phone, department, user_type, status)
VALUES (1, 'admin', '$2a$10$OlfPXeGl2I6aNlrEw514QOGSQBhuYwpu8nIJZYJG7yO/AgJLyRp0u', '系统管理员', 'admin@archive.com', '13800138000', '信息技术部', 'SYSTEM_ADMIN', 'ACTIVE');

INSERT INTO sys_user (id, username, password, real_name, email, phone, department, user_type, status)
VALUES (2, 'testuser', '$2a$10$OlfPXeGl2I6aNlrEw514QOGSQBhuYwpu8nIJZYJG7yO/AgJLyRp0u', '测试用户', 'test@archive.com', '13900139000', '综合部', 'USER', 'ACTIVE');

INSERT INTO sys_role (id, role_code, role_name, description, status) VALUES
(1, 'SYSTEM_ADMIN', '系统管理员', '系统管理员拥有所有权限', 'ACTIVE'),
(2, 'ARCHIVIST', '档案员', '档案管理权限', 'ACTIVE'),
(3, 'USER', '普通用户', '普通用户权限', 'ACTIVE');

INSERT INTO sys_user_role (user_id, role_id) VALUES
(1, 1),
(2, 3);

INSERT INTO sys_config (config_key, config_value, config_type, config_group, description) VALUES
('archive.no.prefix.DEFAULT', 'ARC', 'STRING', 'ARCHIVE_NO', '默认档案号前缀'),
('archive.no.date.format', 'yyyyMMdd', 'STRING', 'ARCHIVE_NO', '档案号日期格式'),
('archive.no.seq.digits', '4', 'NUMBER', 'ARCHIVE_NO', '档案号序号位数'),
('system.upload.max.size', '104857600', 'NUMBER', 'SYSTEM', '最大上传文件大小'),
('system.upload.allowed.types', 'pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip,rar,txt,ofd', 'STRING', 'SYSTEM', '允许上传类型'),
('system.borrow.max.days', '30', 'NUMBER', 'SYSTEM', '最大借阅天数'),
('system.backup.enabled', 'true', 'BOOLEAN', 'SYSTEM', '启用备份中心'),
('system.backup.keep.count', '7', 'NUMBER', 'SYSTEM', '备份保留份数'),
('system.backup.cron', '0 0 2 * * ?', 'STRING', 'SYSTEM', '定时备份 Cron 表达式'),
('system.restore.maintenance.mode', 'true', 'BOOLEAN', 'SYSTEM', '恢复前启用维护模式'),
('system.runtime.maintenance.enabled', 'false', 'BOOLEAN', 'SYSTEM', '系统运行维护模式开关');

INSERT INTO arc_retention_period (id, period_code, period_name, period_years, sort_order) VALUES
(1, 'PERMANENT', '永久', NULL, 1),
(2, 'Y30', '30年', 30, 2),
(3, 'Y15', '15年', 15, 3),
(4, 'Y10', '10年', 10, 4),
(5, 'Y5', '5年', 5, 5);

INSERT INTO arc_fonds (id, fonds_no, fonds_name, description, status)
VALUES (1, 'F001', '律所档案全宗', '律师事务所档案全宗', 'ACTIVE');

INSERT INTO arc_category (id, parent_id, category_code, category_name, archive_type, sort_order, status, level, retention_period, full_path) VALUES
(1, NULL, '01', '诉讼档案', 'DOCUMENT', 1, 'ACTIVE', 1, 'Y10', '01'),
(2, NULL, '02', '非诉档案', 'SPECIAL', 2, 'ACTIVE', 1, 'Y30', '02'),
(3, 1, '0101', '民事诉讼', 'DOCUMENT', 1, 'ACTIVE', 2, 'Y10', '01/0101'),
(4, 1, '0102', '刑事诉讼', 'DOCUMENT', 2, 'ACTIVE', 2, 'Y30', '01/0102');

INSERT INTO archive_location (id, location_code, location_name, room_name, area, shelf_no, layer_no, total_capacity, used_capacity, status)
VALUES (1, 'A-01-01', '一号柜第一层', '主库房', 'A区', '01', '01', 100, 5, 'AVAILABLE');

INSERT INTO arc_archive (
    id, archive_no, fonds_id, fonds_no, category_id, category_code, archive_type, title,
    file_no, responsibility, retention_period, security_level, source_type, status, page_count,
    file_count, archive_form, has_electronic, has_physical, location_id, storage_location, box_no,
    case_no, case_name, client_name, lawyer_name
) VALUES
(1, 'ARC-20260330-0001', 1, 'F001', 3, '0101', 'DOCUMENT', '张三诉李四合同纠纷案',
 'CASE-2026-001', '张律师', 'Y10', 'INTERNAL', 'LAW_FIRM', 'RECEIVED', 50,
 1, 'ELECTRONIC', TRUE, FALSE, 1, '主库房 - 一号柜第一层', 'BOX-001',
 'CASE-2026-001', '张三诉李四合同纠纷案', '张三', '张律师'),
(2, 'ARC-20260330-0002', 1, 'F001', 4, '0102', 'DOCUMENT', '王五故意伤害案',
 'CASE-2026-002', '李律师', 'Y30', 'SECRET', 'LAW_FIRM', 'STORED', 120,
 0, 'HYBRID', TRUE, TRUE, 1, '主库房 - 一号柜第一层', 'BOX-002',
 'CASE-2026-002', '王五故意伤害案', '王五', '李律师');

INSERT INTO arc_digital_file (
    id, archive_id, file_no, file_name, original_name, file_extension, mime_type, file_size,
    storage_path, storage_bucket, format_name, hash_algorithm, hash_value, has_preview,
    file_category, sort_order, file_source_type, upload_at, upload_by, deleted
) VALUES
(1, 1, '001', 'contract.pdf', '合同.pdf', 'pdf', 'application/pdf', 102400,
 'archives/2026/1/contract.pdf', 'test', 'PDF', 'SHA256', 'hash-001', TRUE,
 'MAIN', 1, 'IMPORTED', CURRENT_TIMESTAMP, 1, FALSE),
(2, NULL, '002', 'scan-file.pdf', '扫描件.pdf', 'pdf', 'application/pdf', 204800,
 'archives/2026/tmp/scan-file.pdf', 'test', 'PDF', 'SHA256', 'hash-002', FALSE,
 'MAIN', 1, 'SCANNED', CURRENT_TIMESTAMP, 1, FALSE);

INSERT INTO arc_external_source (id, source_code, source_name, source_type, description, api_url, api_key, auth_type, enabled)
VALUES (1, 'LAW_FIRM_MAIN', '律所管理系统', 'LAW_FIRM', '测试外部来源', 'http://localhost/api', 'test-api-key', 'API_KEY', TRUE);
