# Elasticsearch with IK Analyzer
FROM elasticsearch:8.12.0

# 安装 IK 中文分词器插件
RUN elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.12.0

ENV discovery.type=single-node
ENV xpack.security.enabled=false
ENV xpack.ml.enabled=false
ENV ES_JAVA_OPTS="-Xms192m -Xmx192m"
ENV cluster.name=archive-cluster
