/**
 * 行政诉讼案由
 * 根据行政诉讼法相关规定
 */
import type { CauseCategory } from './types';

/** 行政案由分类 */
export const ADMIN_CAUSES: CauseCategory[] = [
  {
    code: 'A01',
    name: '行政处罚',
    causes: [
      { code: '1', name: '警告' },
      { code: '2', name: '通报批评' },
      { code: '3', name: '罚款' },
      { code: '4', name: '没收违法所得' },
      { code: '5', name: '没收非法财物' },
      { code: '6', name: '暂扣许可证件' },
      { code: '7', name: '吊销许可证件' },
      { code: '8', name: '降低资质等级' },
      { code: '9', name: '责令关闭' },
      { code: '10', name: '责令停产停业' },
      { code: '11', name: '限制开展生产经营活动' },
      { code: '12', name: '限制从业' },
      { code: '13', name: '行政拘留' },
      { code: '14', name: '不得申请行政许可' },
      { code: '15', name: '责令限期拆除' },
    ],
  },
  {
    code: 'A02',
    name: '行政强制措施',
    causes: [
      { code: '16', name: '限制人身自由' },
      { code: '17', name: '查封场所、设施或者财物' },
      { code: '18', name: '扣押财物' },
      { code: '19', name: '冻结存款、汇款' },
      { code: '20', name: '冻结资金、证券' },
      { code: '21', name: '强制隔离戒毒' },
      { code: '22', name: '留置' },
      { code: '23', name: '采取保护性约束措施' },
    ],
  },
  {
    code: 'A03',
    name: '行政强制执行',
    causes: [
      { code: '24', name: '加处罚款或者滞纳金' },
      { code: '25', name: '划拨存款、汇款' },
      { code: '26', name: '拍卖查封、扣押的场所、设施或者财物' },
      { code: '27', name: '处理查封、扣押的场所、设施或者财物' },
      { code: '28', name: '排除妨碍' },
      { code: '29', name: '恢复原状' },
      { code: '30', name: '代履行' },
      { code: '31', name: '强制拆除房屋或者设施' },
      { code: '32', name: '强制清除地上物' },
    ],
  },
  {
    code: 'A04',
    name: '行政许可',
    causes: [
      { code: '33', name: '工商登记' },
      { code: '34', name: '社会团体登记' },
      { code: '35', name: '颁发机动车驾驶证' },
      { code: '36', name: '特许经营许可' },
      { code: '37', name: '建设工程规划许可' },
      { code: '38', name: '建筑工程施工许可' },
      { code: '39', name: '矿产资源许可' },
      { code: '40', name: '药品注册许可' },
      { code: '41', name: '医疗器械许可' },
      { code: '42', name: '执业资格许可' },
    ],
  },
  {
    code: 'A05',
    name: '行政征收或者征用',
    causes: [
      { code: '43', name: '征收或者征用房屋' },
      { code: '44', name: '征收或者征用土地' },
      { code: '45', name: '征收或者征用动产' },
    ],
  },
  {
    code: 'A06',
    name: '行政登记',
    causes: [
      { code: '46', name: '房屋所有权登记' },
      { code: '47', name: '集体土地所有权登记' },
      { code: '48', name: '森林、林木所有权登记' },
      { code: '49', name: '矿业权登记' },
      { code: '50', name: '土地承包经营权登记' },
      { code: '51', name: '建设用地使用权登记' },
      { code: '52', name: '宅基地使用权登记' },
      { code: '53', name: '海域使用权登记' },
      { code: '54', name: '水利工程登记' },
      { code: '55', name: '居住权登记' },
      { code: '56', name: '地役权登记' },
      { code: '57', name: '不动产抵押登记' },
      { code: '58', name: '动产抵押登记' },
      { code: '59', name: '质押登记' },
      { code: '60', name: '机动车所有权登记' },
      { code: '61', name: '船舶所有权登记' },
      { code: '62', name: '户籍登记' },
      { code: '63', name: '婚姻登记' },
      { code: '64', name: '收养登记' },
      { code: '65', name: '税务登记' },
    ],
  },
  {
    code: 'A07',
    name: '行政确认',
    causes: [
      { code: '66', name: '基本养老保险资格或者待遇认定' },
      { code: '67', name: '基本医疗保险资格或者待遇认定' },
      { code: '68', name: '失业保险资格或者待遇认定' },
      { code: '69', name: '工伤保险资格或者待遇认定' },
      { code: '70', name: '生育保险资格或者待遇认定' },
      { code: '71', name: '最低生活保障资格或者待遇认定' },
      { code: '72', name: '确认保障性住房分配资格' },
      { code: '73', name: '颁发学位证书或者毕业证书' },
    ],
  },
  {
    code: 'A08',
    name: '行政给付',
    causes: [
      { code: '74', name: '给付抚恤金' },
      { code: '75', name: '给付基本养老金' },
      { code: '76', name: '给付基本医疗保险金' },
      { code: '77', name: '给付失业保险金' },
      { code: '78', name: '给付工伤保险金' },
      { code: '79', name: '给付生育保险金' },
      { code: '80', name: '给付最低生活保障金' },
    ],
  },
  {
    code: 'A09',
    name: '行政允诺',
    causes: [
      { code: '81', name: '兑现奖金' },
      { code: '82', name: '兑现优惠' },
    ],
  },
  {
    code: 'A10',
    name: '行政征缴',
    causes: [
      { code: '83', name: '征缴税款' },
      { code: '84', name: '征缴社会抚养费' },
      { code: '85', name: '征缴社会保险费' },
      { code: '86', name: '征缴污水处理费' },
      { code: '87', name: '征缴防空地下室易地建设费' },
      { code: '88', name: '征缴水土保持补偿费' },
      { code: '89', name: '征缴土地闲置费' },
      { code: '90', name: '征缴土地复垦费' },
      { code: '91', name: '征缴耕地开垦费' },
    ],
  },
  {
    code: 'A11',
    name: '行政奖励',
    causes: [
      { code: '92', name: '授予荣誉称号' },
      { code: '93', name: '发放奖金' },
    ],
  },
  {
    code: 'A12',
    name: '行政收费',
    causes: [
      { code: '94', name: '证照费' },
      { code: '95', name: '车辆通行费' },
      { code: '96', name: '企业注册登记费' },
      { code: '97', name: '不动产登记费' },
      { code: '98', name: '船舶登记费' },
      { code: '99', name: '考试考务费' },
    ],
  },
  {
    code: 'A13',
    name: '政府信息公开',
    causes: [
      { code: '100', name: '政府信息公开' },
    ],
  },
  {
    code: 'A14',
    name: '行政批复',
    causes: [
      { code: '101', name: '行政批复' },
    ],
  },
  {
    code: 'A15',
    name: '行政处理',
    causes: [
      { code: '102', name: '责令退还非法占用土地' },
      { code: '103', name: '责令交还土地' },
      { code: '104', name: '责令改正' },
      { code: '105', name: '责令采取补救措施' },
      { code: '106', name: '责令停止建设' },
      { code: '107', name: '责令恢复原状' },
      { code: '108', name: '责令公开' },
      { code: '109', name: '责令召回' },
      { code: '110', name: '责令暂停生产' },
      { code: '111', name: '责令暂停销售' },
      { code: '112', name: '责令暂停使用' },
      { code: '113', name: '有偿收回国有土地使用权' },
      { code: '114', name: '退学决定' },
    ],
  },
  {
    code: 'A16',
    name: '行政复议',
    causes: [
      { code: '115', name: '不予受理行政复议申请决定' },
      { code: '116', name: '驳回行政复议申请决定' },
      { code: '117', name: '行政行为及行政复议' },
      { code: '118', name: '改变原行政行为的行政复议决定' },
    ],
  },
  {
    code: 'A17',
    name: '行政裁决',
    causes: [
      { code: '119', name: '土地、矿藏、水流、荒地或者滩涂权属确权' },
      { code: '120', name: '林地、林木、山岭权属确权' },
      { code: '121', name: '海域使用权确权' },
      { code: '122', name: '草原权属确权' },
      { code: '123', name: '水利工程权属确权' },
      { code: '124', name: '企业资产性质确认' },
    ],
  },
  {
    code: 'A18',
    name: '行政协议',
    causes: [
      { code: '125', name: '订立行政协议' },
      { code: '126', name: '单方变更行政协议' },
      { code: '127', name: '单方解除行政协议' },
      { code: '128', name: '不依法履行行政协议' },
      { code: '129', name: '未按约定履行行政协议' },
      { code: '130', name: '行政协议行政补偿' },
      { code: '131', name: '行政协议行政赔偿' },
      { code: '132', name: '撤销行政协议' },
      { code: '133', name: '解除行政协议' },
      { code: '134', name: '继续履行行政协议' },
      { code: '135', name: '确认行政协议无效或有效' },
    ],
  },
  {
    code: 'A19',
    name: '行政补偿',
    causes: [
      { code: '136', name: '房屋征收或者征用补偿' },
      { code: '137', name: '土地征收或者征用补偿' },
      { code: '138', name: '动产征收或者征用补偿' },
      { code: '139', name: '撤回行政许可补偿' },
      { code: '140', name: '收回国有土地使用权补偿' },
      { code: '141', name: '规划变更补偿' },
      { code: '142', name: '移民安置补偿' },
    ],
  },
  {
    code: 'A20',
    name: '行政赔偿',
    causes: [
      { code: '143', name: '行政赔偿' },
    ],
  },
  {
    code: 'A21',
    name: '不履行职责',
    causes: [
      { code: '144', name: '不履行法定职责' },
    ],
  },
  {
    code: 'A22',
    name: '行政公益诉讼',
    causes: [
      { code: '145', name: '行政行为公益诉讼' },
    ],
  },
];
