spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  sql:
    init:
      mode: always
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.lawfirm: debug
    org.springframework: info
